workflows:
  ios-app:
    name: Amadeuse Music
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "com.amadeuse.music" --type IOS_APP_DEVELOPMENT --create
      - name: Set up code signing
        script: |
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA
        script: |
          flutter build ipa --export-method development
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Build/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        # You can find the issuer ID in App Store Connect > Users and Access > Keys
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        # You can find the key ID in App Store Connect > Users and Access > Keys
        key_id: $APP_STORE_CONNECT_KEY_ID