workflows:
  ios-app:
    name: Amadeuse Music
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files "com.anandnet.harmonymusic" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Create export options plist
        script: |
          cat > /tmp/export_options.plist <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadBitcode</key>
              <true/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOL
      - name: Build ipa for App Store
        script: |
          flutter build ipa --release --export-options-plist=/tmp/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Build/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        # You can find the issuer ID in App Store Connect > Users and Access > Keys
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        # You can find the key ID in App Store Connect > Users and Access > Keys
        key_id: $APP_STORE_CONNECT_KEY_ID