workflows:
  ios-app:
    name: Amadeuse Music
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Build unsigned IPA
        script: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/Payload/Runner.app
          cd build/ios
          zip -r AmadeuseMusic.ipa Payload
    artifacts:
      - build/ios/AmadeuseMusic.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Build/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        # You can find the issuer ID in App Store Connect > Users and Access > Keys
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        # You can find the key ID in App Store Connect > Users and Access > Keys
        key_id: $APP_STORE_CONNECT_KEY_ID