icon: assets/icons/amadeuse_music.png
summary: AMADEUSE MUSIC - Application de streaming musical
group: Application/Multimedia
vendor: anandnet
packager: anandnet
license: GPLv3
url: https://github.com/anandnet/amadeuse-Music

requires:
  - mpv-libs
  - libappindicator

display_name: AMADEUSE MUSIC

keywords:
  - Opensource
  - Music
  - Streaming
  - Flutter

generic_name: AMADEUSE MUSIC Music Application

categories:
  - Music

startup_notify: true